spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ding_seckill?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

# MyBatis-Plus 配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 控制台打印 SQL，方便调试
  global-config:
    db-config:
      id-type: auto  # 使用数据库自增 ID（对应你写的 AUTO_INCREMENT）
